add: new section named boiler plate with tools to generate projects
thisdot/tech-dev-tooling pull request #29
Opened 2022-10-07 14:17 UTC by simaraconceicao

## Adding new section named boiler plate with tools to generate projects

- [ x ] Link to library is included 
- [ x ] Name of library is included
- [ x] Name and link are spelled correctly

Happy hacktoberfest! 👩🏾‍💻😍

2022-10-07 17:42 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-07 17:42 UTC, jdwilkin4 commented on README.md
> +Create React App is a boiler plate to generate React Apps.
I think these are good additions but let's place it under web dev tools and remove the Boiler Plate category. 👍

2022-10-09 18:26 UTC, simaraconceicao commented
Hey, thanks for the feedback. I did the changes. I hope you aprove.

2022-10-10 16:37 UTC, jdwilkin4 approved these changes
Hi @simaraconceicao ! 

Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-10 16:38 UTC, merged